/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as CommunitiesCommunityIdRouteImport } from './routes/communities/$communityId'
import { Route as ClassesClassIdRouteImport } from './routes/classes/$classId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminClassesIndexRouteImport } from './routes/admin/classes/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminUsersCreateRouteImport } from './routes/admin/users/create'
import { Route as AdminClassesCreateRouteImport } from './routes/admin/classes/create'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as CommunitiesCommunityIdThreadsThreadIdRouteImport } from './routes/communities/$communityId/threads/$threadId'
import { Route as ClassesClassIdUnitsUnitIdRouteImport } from './routes/classes/$classId/units/$unitId'
import { Route as ClassesClassIdTestsTestIdRouteImport } from './routes/classes/$classId/tests/$testId'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users/$userId/edit'
import { Route as AdminClassesClassIdEditRouteImport } from './routes/admin/classes/$classId/edit'
import { Route as AdminClassesClassIdUnitsCreateRouteImport } from './routes/admin/classes/$classId/units/create'
import { Route as AdminClassesClassIdTestsCreateRouteImport } from './routes/admin/classes/$classId/tests/create'
import { Route as ClassesClassIdUnitsUnitIdLessonsLessonIdRouteImport } from './routes/classes/$classId/units/$unitId/lessons/$lessonId'
import { Route as AdminClassesClassIdUnitsUnitIdEditRouteImport } from './routes/admin/classes/$classId/units/$unitId/edit'
import { Route as AdminClassesClassIdUnitsUnitIdLessonsCreateRouteImport } from './routes/admin/classes/$classId/units/$unitId/lessons/create'
import { Route as AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRouteImport } from './routes/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunityIdRoute = CommunitiesCommunityIdRouteImport.update({
  id: '/$communityId',
  path: '/$communityId',
  getParentRoute: () => CommunitiesRoute,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassesIndexRoute = AdminClassesIndexRouteImport.update({
  id: '/admin/classes/',
  path: '/admin/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersCreateRoute = AdminUsersCreateRouteImport.update({
  id: '/admin/users/create',
  path: '/admin/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassesCreateRoute = AdminClassesCreateRouteImport.update({
  id: '/admin/classes/create',
  path: '/admin/classes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunityIdThreadsThreadIdRoute =
  CommunitiesCommunityIdThreadsThreadIdRouteImport.update({
    id: '/threads/$threadId',
    path: '/threads/$threadId',
    getParentRoute: () => CommunitiesCommunityIdRoute,
  } as any)
const ClassesClassIdUnitsUnitIdRoute =
  ClassesClassIdUnitsUnitIdRouteImport.update({
    id: '/units/$unitId',
    path: '/units/$unitId',
    getParentRoute: () => ClassesClassIdRoute,
  } as any)
const ClassesClassIdTestsTestIdRoute =
  ClassesClassIdTestsTestIdRouteImport.update({
    id: '/tests/$testId',
    path: '/tests/$testId',
    getParentRoute: () => ClassesClassIdRoute,
  } as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/admin/users/$userId/edit',
  path: '/admin/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassesClassIdEditRoute = AdminClassesClassIdEditRouteImport.update({
  id: '/admin/classes/$classId/edit',
  path: '/admin/classes/$classId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassesClassIdUnitsCreateRoute =
  AdminClassesClassIdUnitsCreateRouteImport.update({
    id: '/admin/classes/$classId/units/create',
    path: '/admin/classes/$classId/units/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminClassesClassIdTestsCreateRoute =
  AdminClassesClassIdTestsCreateRouteImport.update({
    id: '/admin/classes/$classId/tests/create',
    path: '/admin/classes/$classId/tests/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassesClassIdUnitsUnitIdLessonsLessonIdRoute =
  ClassesClassIdUnitsUnitIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => ClassesClassIdUnitsUnitIdRoute,
  } as any)
const AdminClassesClassIdUnitsUnitIdEditRoute =
  AdminClassesClassIdUnitsUnitIdEditRouteImport.update({
    id: '/admin/classes/$classId/units/$unitId/edit',
    path: '/admin/classes/$classId/units/$unitId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminClassesClassIdUnitsUnitIdLessonsCreateRoute =
  AdminClassesClassIdUnitsUnitIdLessonsCreateRouteImport.update({
    id: '/admin/classes/$classId/units/$unitId/lessons/create',
    path: '/admin/classes/$classId/units/$unitId/lessons/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRoute =
  AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRouteImport.update({
    id: '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit',
    path: '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup-admin': typeof SetupAdminRoute
  '/signup': typeof SignupRoute
  '/classes/$classId': typeof ClassesClassIdRouteWithChildren
  '/communities/$communityId': typeof CommunitiesCommunityIdRouteWithChildren
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/classes/create': typeof AdminClassesCreateRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/classes': typeof AdminClassesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/classes/$classId/edit': typeof AdminClassesClassIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/classes/$classId/tests/$testId': typeof ClassesClassIdTestsTestIdRoute
  '/classes/$classId/units/$unitId': typeof ClassesClassIdUnitsUnitIdRouteWithChildren
  '/communities/$communityId/threads/$threadId': typeof CommunitiesCommunityIdThreadsThreadIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/admin/classes/$classId/tests/create': typeof AdminClassesClassIdTestsCreateRoute
  '/admin/classes/$classId/units/create': typeof AdminClassesClassIdUnitsCreateRoute
  '/admin/classes/$classId/units/$unitId/edit': typeof AdminClassesClassIdUnitsUnitIdEditRoute
  '/classes/$classId/units/$unitId/lessons/$lessonId': typeof ClassesClassIdUnitsUnitIdLessonsLessonIdRoute
  '/admin/classes/$classId/units/$unitId/lessons/create': typeof AdminClassesClassIdUnitsUnitIdLessonsCreateRoute
  '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit': typeof AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup-admin': typeof SetupAdminRoute
  '/signup': typeof SignupRoute
  '/classes/$classId': typeof ClassesClassIdRouteWithChildren
  '/communities/$communityId': typeof CommunitiesCommunityIdRouteWithChildren
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/classes/create': typeof AdminClassesCreateRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/classes': typeof AdminClassesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/classes/$classId/edit': typeof AdminClassesClassIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/classes/$classId/tests/$testId': typeof ClassesClassIdTestsTestIdRoute
  '/classes/$classId/units/$unitId': typeof ClassesClassIdUnitsUnitIdRouteWithChildren
  '/communities/$communityId/threads/$threadId': typeof CommunitiesCommunityIdThreadsThreadIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/admin/classes/$classId/tests/create': typeof AdminClassesClassIdTestsCreateRoute
  '/admin/classes/$classId/units/create': typeof AdminClassesClassIdUnitsCreateRoute
  '/admin/classes/$classId/units/$unitId/edit': typeof AdminClassesClassIdUnitsUnitIdEditRoute
  '/classes/$classId/units/$unitId/lessons/$lessonId': typeof ClassesClassIdUnitsUnitIdLessonsLessonIdRoute
  '/admin/classes/$classId/units/$unitId/lessons/create': typeof AdminClassesClassIdUnitsUnitIdLessonsCreateRoute
  '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit': typeof AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup-admin': typeof SetupAdminRoute
  '/signup': typeof SignupRoute
  '/classes/$classId': typeof ClassesClassIdRouteWithChildren
  '/communities/$communityId': typeof CommunitiesCommunityIdRouteWithChildren
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/classes/create': typeof AdminClassesCreateRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/classes/': typeof AdminClassesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/classes/$classId/edit': typeof AdminClassesClassIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/classes/$classId/tests/$testId': typeof ClassesClassIdTestsTestIdRoute
  '/classes/$classId/units/$unitId': typeof ClassesClassIdUnitsUnitIdRouteWithChildren
  '/communities/$communityId/threads/$threadId': typeof CommunitiesCommunityIdThreadsThreadIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/admin/classes/$classId/tests/create': typeof AdminClassesClassIdTestsCreateRoute
  '/admin/classes/$classId/units/create': typeof AdminClassesClassIdUnitsCreateRoute
  '/admin/classes/$classId/units/$unitId/edit': typeof AdminClassesClassIdUnitsUnitIdEditRoute
  '/classes/$classId/units/$unitId/lessons/$lessonId': typeof ClassesClassIdUnitsUnitIdLessonsLessonIdRoute
  '/admin/classes/$classId/units/$unitId/lessons/create': typeof AdminClassesClassIdUnitsUnitIdLessonsCreateRoute
  '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit': typeof AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/communities'
    | '/dashboard'
    | '/login'
    | '/setup-admin'
    | '/signup'
    | '/classes/$classId'
    | '/communities/$communityId'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/admin/classes/create'
    | '/admin/users/create'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/classes'
    | '/admin/users'
    | '/admin/classes/$classId/edit'
    | '/admin/users/$userId/edit'
    | '/classes/$classId/tests/$testId'
    | '/classes/$classId/units/$unitId'
    | '/communities/$communityId/threads/$threadId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/admin/classes/$classId/tests/create'
    | '/admin/classes/$classId/units/create'
    | '/admin/classes/$classId/units/$unitId/edit'
    | '/classes/$classId/units/$unitId/lessons/$lessonId'
    | '/admin/classes/$classId/units/$unitId/lessons/create'
    | '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/communities'
    | '/dashboard'
    | '/login'
    | '/setup-admin'
    | '/signup'
    | '/classes/$classId'
    | '/communities/$communityId'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/admin/classes/create'
    | '/admin/users/create'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/classes'
    | '/admin/users'
    | '/admin/classes/$classId/edit'
    | '/admin/users/$userId/edit'
    | '/classes/$classId/tests/$testId'
    | '/classes/$classId/units/$unitId'
    | '/communities/$communityId/threads/$threadId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/admin/classes/$classId/tests/create'
    | '/admin/classes/$classId/units/create'
    | '/admin/classes/$classId/units/$unitId/edit'
    | '/classes/$classId/units/$unitId/lessons/$lessonId'
    | '/admin/classes/$classId/units/$unitId/lessons/create'
    | '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit'
  id:
    | '__root__'
    | '/'
    | '/communities'
    | '/dashboard'
    | '/login'
    | '/setup-admin'
    | '/signup'
    | '/classes/$classId'
    | '/communities/$communityId'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/admin/classes/create'
    | '/admin/users/create'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/classes/'
    | '/admin/users/'
    | '/admin/classes/$classId/edit'
    | '/admin/users/$userId/edit'
    | '/classes/$classId/tests/$testId'
    | '/classes/$classId/units/$unitId'
    | '/communities/$communityId/threads/$threadId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/admin/classes/$classId/tests/create'
    | '/admin/classes/$classId/units/create'
    | '/admin/classes/$classId/units/$unitId/edit'
    | '/classes/$classId/units/$unitId/lessons/$lessonId'
    | '/admin/classes/$classId/units/$unitId/lessons/create'
    | '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SignupRoute: typeof SignupRoute
  ClassesClassIdRoute: typeof ClassesClassIdRouteWithChildren
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AdminClassesCreateRoute: typeof AdminClassesCreateRoute
  AdminUsersCreateRoute: typeof AdminUsersCreateRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  AdminClassesIndexRoute: typeof AdminClassesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminClassesClassIdEditRoute: typeof AdminClassesClassIdEditRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
  AdminClassesClassIdTestsCreateRoute: typeof AdminClassesClassIdTestsCreateRoute
  AdminClassesClassIdUnitsCreateRoute: typeof AdminClassesClassIdUnitsCreateRoute
  AdminClassesClassIdUnitsUnitIdEditRoute: typeof AdminClassesClassIdUnitsUnitIdEditRoute
  AdminClassesClassIdUnitsUnitIdLessonsCreateRoute: typeof AdminClassesClassIdUnitsUnitIdLessonsCreateRoute
  AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRoute: typeof AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communityId': {
      id: '/communities/$communityId'
      path: '/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof CommunitiesCommunityIdRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes/': {
      id: '/admin/classes/'
      path: '/admin/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/admin/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminUsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes/create': {
      id: '/admin/classes/create'
      path: '/admin/classes/create'
      fullPath: '/admin/classes/create'
      preLoaderRoute: typeof AdminClassesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communityId/threads/$threadId': {
      id: '/communities/$communityId/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/communities/$communityId/threads/$threadId'
      preLoaderRoute: typeof CommunitiesCommunityIdThreadsThreadIdRouteImport
      parentRoute: typeof CommunitiesCommunityIdRoute
    }
    '/classes/$classId/units/$unitId': {
      id: '/classes/$classId/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/classes/$classId/units/$unitId'
      preLoaderRoute: typeof ClassesClassIdUnitsUnitIdRouteImport
      parentRoute: typeof ClassesClassIdRoute
    }
    '/classes/$classId/tests/$testId': {
      id: '/classes/$classId/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/classes/$classId/tests/$testId'
      preLoaderRoute: typeof ClassesClassIdTestsTestIdRouteImport
      parentRoute: typeof ClassesClassIdRoute
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/admin/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes/$classId/edit': {
      id: '/admin/classes/$classId/edit'
      path: '/admin/classes/$classId/edit'
      fullPath: '/admin/classes/$classId/edit'
      preLoaderRoute: typeof AdminClassesClassIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes/$classId/units/create': {
      id: '/admin/classes/$classId/units/create'
      path: '/admin/classes/$classId/units/create'
      fullPath: '/admin/classes/$classId/units/create'
      preLoaderRoute: typeof AdminClassesClassIdUnitsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes/$classId/tests/create': {
      id: '/admin/classes/$classId/tests/create'
      path: '/admin/classes/$classId/tests/create'
      fullPath: '/admin/classes/$classId/tests/create'
      preLoaderRoute: typeof AdminClassesClassIdTestsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/units/$unitId/lessons/$lessonId': {
      id: '/classes/$classId/units/$unitId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/classes/$classId/units/$unitId/lessons/$lessonId'
      preLoaderRoute: typeof ClassesClassIdUnitsUnitIdLessonsLessonIdRouteImport
      parentRoute: typeof ClassesClassIdUnitsUnitIdRoute
    }
    '/admin/classes/$classId/units/$unitId/edit': {
      id: '/admin/classes/$classId/units/$unitId/edit'
      path: '/admin/classes/$classId/units/$unitId/edit'
      fullPath: '/admin/classes/$classId/units/$unitId/edit'
      preLoaderRoute: typeof AdminClassesClassIdUnitsUnitIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes/$classId/units/$unitId/lessons/create': {
      id: '/admin/classes/$classId/units/$unitId/lessons/create'
      path: '/admin/classes/$classId/units/$unitId/lessons/create'
      fullPath: '/admin/classes/$classId/units/$unitId/lessons/create'
      preLoaderRoute: typeof AdminClassesClassIdUnitsUnitIdLessonsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit': {
      id: '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit'
      path: '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit'
      fullPath: '/admin/classes/$classId/units/$unitId/lessons/$lessonId/edit'
      preLoaderRoute: typeof AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommunitiesCommunityIdRouteChildren {
  CommunitiesCommunityIdThreadsThreadIdRoute: typeof CommunitiesCommunityIdThreadsThreadIdRoute
}

const CommunitiesCommunityIdRouteChildren: CommunitiesCommunityIdRouteChildren =
  {
    CommunitiesCommunityIdThreadsThreadIdRoute:
      CommunitiesCommunityIdThreadsThreadIdRoute,
  }

const CommunitiesCommunityIdRouteWithChildren =
  CommunitiesCommunityIdRoute._addFileChildren(
    CommunitiesCommunityIdRouteChildren,
  )

interface CommunitiesRouteChildren {
  CommunitiesCommunityIdRoute: typeof CommunitiesCommunityIdRouteWithChildren
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesCommunityIdRoute: CommunitiesCommunityIdRouteWithChildren,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface ClassesClassIdUnitsUnitIdRouteChildren {
  ClassesClassIdUnitsUnitIdLessonsLessonIdRoute: typeof ClassesClassIdUnitsUnitIdLessonsLessonIdRoute
}

const ClassesClassIdUnitsUnitIdRouteChildren: ClassesClassIdUnitsUnitIdRouteChildren =
  {
    ClassesClassIdUnitsUnitIdLessonsLessonIdRoute:
      ClassesClassIdUnitsUnitIdLessonsLessonIdRoute,
  }

const ClassesClassIdUnitsUnitIdRouteWithChildren =
  ClassesClassIdUnitsUnitIdRoute._addFileChildren(
    ClassesClassIdUnitsUnitIdRouteChildren,
  )

interface ClassesClassIdRouteChildren {
  ClassesClassIdTestsTestIdRoute: typeof ClassesClassIdTestsTestIdRoute
  ClassesClassIdUnitsUnitIdRoute: typeof ClassesClassIdUnitsUnitIdRouteWithChildren
}

const ClassesClassIdRouteChildren: ClassesClassIdRouteChildren = {
  ClassesClassIdTestsTestIdRoute: ClassesClassIdTestsTestIdRoute,
  ClassesClassIdUnitsUnitIdRoute: ClassesClassIdUnitsUnitIdRouteWithChildren,
}

const ClassesClassIdRouteWithChildren = ClassesClassIdRoute._addFileChildren(
  ClassesClassIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SetupAdminRoute: SetupAdminRoute,
  SignupRoute: SignupRoute,
  ClassesClassIdRoute: ClassesClassIdRouteWithChildren,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AdminClassesCreateRoute: AdminClassesCreateRoute,
  AdminUsersCreateRoute: AdminUsersCreateRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  AdminClassesIndexRoute: AdminClassesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminClassesClassIdEditRoute: AdminClassesClassIdEditRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
  AdminClassesClassIdTestsCreateRoute: AdminClassesClassIdTestsCreateRoute,
  AdminClassesClassIdUnitsCreateRoute: AdminClassesClassIdUnitsCreateRoute,
  AdminClassesClassIdUnitsUnitIdEditRoute:
    AdminClassesClassIdUnitsUnitIdEditRoute,
  AdminClassesClassIdUnitsUnitIdLessonsCreateRoute:
    AdminClassesClassIdUnitsUnitIdLessonsCreateRoute,
  AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRoute:
    AdminClassesClassIdUnitsUnitIdLessonsLessonIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
